export const productCategories = [
  {
    name: 'Tendências de Mercado',
    imagem: require('../assets/images/trending.png'),
    id: 1,
    category: 'trending',
  },
  {
    name: 'Empresas & Estabelecimentos Comerciais',
    imagem: require('../assets/images/companies.png'),
    id: 2,
    category: 'company',
  },
  {
    name: 'Automóveis & Veículos',
    imagem: require('../assets/images/vehicles.png'),
    id: 3,
    category: 'vehicle',
  },
  {
    name: 'Casas, Terrenos & Imóveis',
    imagem: require('../assets/images/property.png'),
    id: 4,
    category: 'property',
  },
  {
    name: 'Mobiliários, Electrodomésticos & Utensílios',
    imagem: require('../assets/images/house-furniture.png'),
    id: 5,
    category: 'houseware',
  },
  {
    name: 'Telemóveis & Computadores',
    imagem: require('../assets/images/computers.png'),
    id: 6,
    category: 'computer',
  },

  {
    name: 'Equipamentos Electrónicos',
    imagem: require('../assets/images/electronics.png'),
    id: 8,
    category: 'electronic',
  },
  {
    name: 'Cosméticos, Cabelo & Beleza',
    imagem: require('../assets/images/beauty.png'),
    id: 9,
    category: 'beauty',
  },
  {
    name: 'Saúde',
    imagem: require('../assets/images/fitness.png'),
    id: 10,
    category: 'health',
  },
  {
    name: 'Roupas, Estilos & Modas',
    imagem: require('../assets/images/fashion.png'),
    id: 11,
    category: 'fashion',
  },
  {
    name: 'Infantis & Crianças',
    imagem: require('../assets/images/babies.png'),
    id: 12,
    category: 'kid',
  },
  {
    name: 'Empregos',
    imagem: require('../assets/images/job-seeker.png'),
    id: 13,
    category: 'job',
  },
  {
    name: 'Candidatos a Empregos - CVs',
    imagem: require('../assets/images/jobs.png'),
    id: 14,
    category: 'job-seeker',
  },
  {
    name: 'Esporte & Lazer',
    imagem: require('../assets/images/hobbies.png'),
    id: 15,
    category: 'leisure',
  },
  {
    name: 'Prestação de Serviços',
    imagem: require('../assets/images/services.png'),
    id: 16,
    category: 'service',
  },
  {
    name: 'Agronegócio',
    imagem: require('../assets/images/agriculture.png'),
    id: 17,
    category: 'agrobusiness',
  },
  {
    name: 'Alimentos',
    imagem: require('../assets/images/agriculture.png'),
    id: 17,
    category: 'food',
  },
  {
    name: 'Bebidas, Sumos & Água',
    imagem: require('../assets/images/drink.png'),
    id: 17,
    category: 'drink',
  },
  {
    name: 'Animais de Estimação',
    imagem: require('../assets/images/pets.png'),
    id: 18,
    category: 'pet',
  },
  {
    name: 'Construção & Reparação',
    imagem: require('../assets/images/repairing.png'),
    id: 20,
    category: 'construction',
  },
  {
    name: 'Educação',
    imagem: require('../assets/images/equipments.png'),
    id: 19,
    category: 'education',
  },
];
